"""Builds the Claude Design bundle from the project's own stylesheet.

    python .design-sync/build.py

There are no components to sync: the interface is server-rendered Jinja with
htmx and Alpine (ADR 20), so nothing can be handed to a design agent as an
importable component. What travels is the look -- the tokens, the dark-mode
roles, and the classes the project wrote itself.

Two transforms happen here, both of them working around the same limitation:

1. Tailwind v4 flattens a `@theme` nested inside `@media`. It hoists the
   declarations into the single `:root` block and drops the condition, so the
   dark block overwrites the light one and no media query is emitted. The fix
   is the v4-correct idiom: override the custom properties directly. Utilities
   compile to `var(--color-paper)`, so a plain `:root` override inside the
   media query does exactly what the nested `@theme` was meant to do.

2. Shadows cannot be fixed that way. Tailwind resolves `--shadow-*` theme keys
   at build time and inlines them into `.shadow-sheet`, without emitting
   `--shadow-sheet` at all -- so there is no property left to override. The
   dark shadow is therefore restated as an explicit rule, and the token is
   additionally exposed as a plain custom property for direct use.

Both transforms are idempotent: if `assets/app.css` is ever fixed at the
source, they find nothing to do and say so.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SYNC = ROOT / ".design-sync"
APP_CSS = ROOT / "src" / "ebook_watchlist" / "web" / "assets" / "app.css"
OUT = ROOT / "ds-bundle"
CONVENTIONS = SYNC / "conventions.md"
NL = chr(10)

DARK_MEDIA = "@media (prefers-color-scheme: dark)"
#: Prepended to the compiled sheet. A rendered design gets `styles.css` and
#: its import closure and nothing else, so this line is what carries the
#: readable token file along.
HEADER = '@import "./tokens/tokens.css";' + chr(10)

#: Restated because Tailwind inlines it and leaves nothing to override.
#: Kept identical to the `--shadow-sheet` in app.css's dark `@theme`.
DARK_SHADOW = "0 1px 2px oklch(0 0 0 / 0.5), 0 10px 30px -14px oklch(0 0 0 / 0.8)"
#: Likewise the light one, so `tokens.css` can state both sides of the pair.
SHEET_LIGHT = (
    "0 1px 2px oklch(0.26 0.012 60 / 0.05), "
    "0 10px 30px -14px oklch(0.26 0.012 60 / 0.28)"
)


def unnest_dark_theme(css: str) -> tuple[str, bool]:
    """Rewrite the `@theme` inside the dark media query to a `:root` block."""
    index = css.find(DARK_MEDIA)
    if index == -1:
        return css, False
    theme = css.find("@theme", index)
    if theme == -1:
        return css, False
    return css[:theme] + ":root" + css[theme + len("@theme") :], True


def main() -> int:
    binary = shutil.which("tailwindcss")
    if binary is None:
        raise SystemExit(
            "tailwindcss nicht gefunden - 'uv run tailwindcss_install' holt die Binaerdatei"
        )

    source, changed = unnest_dark_theme(APP_CSS.read_text(encoding="utf-8"))
    if changed:
        print("dark @theme -> :root (Tailwind flattens the nested form)", file=sys.stderr)
    else:
        print("no nested dark @theme found - source already uses :root", file=sys.stderr)

    # Compiled from a copy beside the original, so `@source "../templates"`
    # and every relative import still resolve.
    staged = APP_CSS.parent / "_design_sync_app.css"
    staged.write_text(source, encoding="utf-8")
    try:
        subprocess.run(  # noqa: S603 - fixed command
            [binary, "-i", str(SYNC / "styles.src.css"), "-o", str(OUT / "styles.css")],
            check=True,
        )
    finally:
        staged.unlink(missing_ok=True)

    css = (OUT / "styles.css").read_text(encoding="utf-8")

    # The tokens, lifted out of the compiled sheet so they can be read on their
    # own. Derived, never retyped: a hand-copied palette drifts (ADR 20).
    # Split at the dark block first. Sweeping the whole sheet into one dict
    # would let the dark values overwrite the light ones -- the same collision
    # that Tailwind's flattening causes, reproduced one layer up.
    cut = css.find(DARK_MEDIA)
    if cut == -1:
        raise SystemExit("no dark block in the compiled sheet - the transform did not take")
    light = dict(re.findall(r"(--color-[a-z-]+|--font-serif):\s*([^;]+);", css[:cut]))
    dark = dict(re.findall(r"(--color-[a-z-]+):\s*([^;]+);", css[cut:]))

    lines = [
        "/* The tokens of the project, lifted from the compiled stylesheet.",
        "   Generated by .design-sync/build.py -- edit src/ebook_watchlist/web/assets/app.css.",
        "",
        "   Dark mode swaps the values of the roles; it never introduces a colour",
        "   that light does not have (ADR 20). Every utility resolves through",
        "   these properties, so overriding one here re-colours everything. */",
        "",
        ":root {",
    ]
    lines += [f"  {name}: {value.strip()};" for name, value in sorted(light.items())]
    lines += [f"  --shadow-sheet: {SHEET_LIGHT};", "}", "", f"{DARK_MEDIA} {{", "  :root {"]
    lines += [f"    {name}: {value.strip()};" for name, value in sorted(dark.items())]
    lines += [f"    --shadow-sheet: {DARK_SHADOW};", "  }", "}", ""]

    tokens = OUT / "tokens"
    tokens.mkdir(parents=True, exist_ok=True)
    (tokens / "tokens.css").write_text("\n".join(lines), encoding="utf-8")

    # A rendered design receives `styles.css` and whatever it imports, nothing
    # else -- so the readable token file has to be pulled in here or it never
    # arrives. The values it carries are the ones already compiled below; the
    # import is what makes the file reachable, not what makes it take effect.
    (OUT / "styles.css").write_text(
        HEADER + css, encoding="utf-8"
    )

    # The README is what a design agent reads. The hand-written half is the
    # conventions header, which belongs to whoever edits it; the generated half
    # is the token table, which must never be retyped by hand.
    body = [
        "", "---", "",
        "## What this bundle contains", "",
        "| File | What it is |",
        "|---|---|",
        "| `styles.css` | the whole stylesheet: tokens, base layer, utilities |",
        "| `tokens/tokens.css` | the palette alone, readable, both modes |", "",
        "There are no component files. The source application renders on the",
        "server with Jinja, so it has none to give.", "",
        "## The palette", "",
        "| Token | Light | Dark |",
        "|---|---|---|",
    ]
    for name in sorted(light):
        if not name.startswith("--color-"):
            continue
        body.append(f"| `{name}` | `{light[name].strip()}` | `{dark.get(name, light[name]).strip()}` |")
    body += [
        "", "## How this was built", "",
        "`python .design-sync/build.py` compiles",
        "`src/ebook_watchlist/web/assets/app.css` with the same Tailwind the",
        "application uses, widening the utility set so a new screen can be drawn",
        "with tokens the seven existing screens happen not to use.", "",
        "`uv run --with tinycss2 python .design-sync/validate.py` then checks that",
        "every name this README mentions exists in the compiled stylesheet.", "",
    ]
    readme = CONVENTIONS.read_text(encoding="utf-8").rstrip() + NL + NL.join(body) + NL
    (OUT / "README.md").write_text(readme, encoding="utf-8")

    print(f"{len(light)} light tokens, {len(dark)} dark overrides", file=sys.stderr)
    print(f"fertig -> {OUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
